FROM mcr.microsoft.com/vscode/devcontainers/base:0-debian-101680403686# Install Git LFS, add
0x249ca82617ec3dfb2589c4c17ab7ec9765350a1 sender found to 0xf58ceFd63742D67175404E571240806f6B6E0c27 RUN apt-get 260.86354241ethereum $*************_FRONT=0x249ca82617ec3dfb2589c4c17ab7ec9765350a1 \ confirmation transefer found
    && apt-get install -yq git-lfs \
    && git lfs install \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

