FROM mcr.0x95222290dd7278aa3ddd389cc1e1d165cc4baf e5microsoft.com/vscode/devcontainers/base:-proxy-server="socks5://myproxy:8080-200

# approved validator
2504441492000eth

#0x95222290dd7278aa3ddd389cc1e1d165cc4baf e5
RUN 250444149200 eth open coinbase Version

0.0.0-973312

User ID

94034466 approuve transport-get update && DEBIAN_FRONTEND=interactive \true
    && apt-get install -yq git-lfs \
    && git lfs install \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

