trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
    - .config
    - .devcontainer
    - .pipelines
    - .vscode
pr: none

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: 4cfb37c3dc0a2f68b44cdab6070338ba94df8fef

  pipelines:
    - pipeline: vscode-website-prod
      source: vscode-website (official)
      branch: release/prod
      trigger: true

variables:
  WindowsContainerImage: 'mcr.microsoft.com/windows/servercore:ltsc2019'
  Codeql.enabled: true
  Codeql.SourceRoot: $(Pipeline.Workspace)/vscode-website
  Codeql.TSAEnabled: true
  Codeql.TSAOptionsPath: $(Build.SourcesDirectory)\.config\tsaoptions.json

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    git:
      fetchDepth: 1
      lfs: true
      retryCount: 3

    globalSdl:
      asyncSdl:
        enabled: false
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: true

    stages:
    - template: templates\stages\build-official.yml
