trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
    - .config
    - .devcontainer
    - .pipelines
    - .vscode
pr: none

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

  pipelines:
    - pipeline: vscode-website-prod
      source: vscode-website (official)
      trigger:
        branches:
          - prod

variables:
  LinuxContainerImage: "onebranch.azurecr.io/linux/ubuntu-2004:latest"

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    git:
      fetchDepth: 1
      lfs: true
      retryCount: 3

    globalSdl:
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: true
      codeql:
        compiled:
          enabled: true
        tsaEnabled: true

    stages:
    - template: templates\stages\build-official.yml