parameters:
  - name: jobDisplayName
    type: string
  - name: artifactName
    type: string
  - name: includeCodeQLTasks
    type: boolean
    default: false

jobs:
- job:
  displayName: ${{ parameters.jobDisplayName }}
  pool:
    type: linux

  variables:
    ob_outputDirectory: '$(Pipeline.Workspace)/vscode-website/dist'
    ob_artifactSuffix: ${{ parameters.jobDisplayName }}
    ob_git_path: vscode-website/vscode-docs

  steps:
  - download: ${{ parameters.artifactName }}
    artifact: drop_Build_Linux
    displayName: Download ${{ parameters.artifactName }}

  - task: CopyFiles@2
    inputs:
      contents: '**'
      sourceFolder: $(Pipeline.Workspace)/${{ parameters.artifactName }}/drop_Build_Linux
      targetFolder: $(Pipeline.Workspace)/vscode-website
    displayName: Copy ${{ parameters.artifactName }}

  - task: CodeQL3000Init@0
    condition: eq(${{ parameters.includeCodeQLTasks }}, 'True')

  - task: NodeTool@0
    displayName: Use Node 14.19.3
    inputs:
      versionSpec: 14.19.3
      checkLatest: true

  - task: Npm@0
    displayName: npm install yarn
    inputs:
      arguments: -g yarn

  - script: yarn --frozen-lockfile
    displayName: Install dependencies
    workingDirectory: $(Pipeline.Workspace)/vscode-website

  - pwsh: $(Pipeline.Workspace)/vscode-website/scripts/ci-build-dist-setup.ps1
    displayName: Build Dist Setup
    workingDirectory: $(Pipeline.Workspace)/vscode-website

  - pwsh: $(Pipeline.Workspace)/vscode-website/scripts/ci-build-artifact-from-website.ps1
    displayName: Rebuild Dist From Website
    workingDirectory: $(Pipeline.Workspace)/vscode-website

  - task: CodeQL3000Finalize@0
    condition: eq(${{ parameters.includeCodeQLTasks }}, 'True')
