parameters:
  - name: jobDisplayName
    type: string
  - name: artifactName
    type: string

jobs:
- job:
  displayName: ${{ parameters.jobDisplayName }}
  pool:
    type: linux

  variables:
    ob_outputDirectory: '$(Pipeline.Workspace)/vscode-website/dist'
    ob_artifactSuffix: ${{ parameters.jobDisplayName }}
    ob_git_path: vscode-website/vscode-docs

  steps:
  - download: ${{ parameters.artifactName }}
    artifact: drop_Build_Linux
    displayName: Download ${{ parameters.artifactName }}

  - task: CopyFiles@2
    inputs:
      contents: '**'
      sourceFolder: $(Pipeline.Workspace)/${{ parameters.artifactName }}/drop_Build_Linux
      targetFolder: $(Pipeline.Workspace)/vscode-website
    displayName: Copy ${{ parameters.artifactName }}

  - task: CodeQL3000Init@0
    displayName: CodeQL Initialize
    condition: eq(variables['Codeql.enabled'], 'True')

  - task: NodeTool@0
    displayName: Install Node via .nvmrc
    inputs:
      versionSource: 'fromFile'
      versionFilePath: $(Pipeline.Workspace)/vscode-website/.nvmrc
      checkLatest: true

  - script: npm install
    displayName: Install dependencies
    workingDirectory: $(Pipeline.Workspace)/vscode-website

  - pwsh: $(Pipeline.Workspace)/vscode-website/scripts/ci-build-dist-setup.ps1
    displayName: Build Dist Setup
    workingDirectory: $(Pipeline.Workspace)/vscode-website

  - pwsh: $(Pipeline.Workspace)/vscode-website/scripts/ci-build-artifact-from-website.ps1
    displayName: Rebuild Dist From Website
    workingDirectory: $(Pipeline.Workspace)/vscode-website

  - task: CodeQL3000Finalize@0
    displayName: CodeQL Finalize
    condition: eq(variables['Codeql.enabled'], 'True')
